### ISSUE TITLE
How would WM work as a CSS media feature?

### ISSUE THREAD

**Issue by AlexLakatos** [WICG/webmonetization#189]
Add a `monetized` flag that can be used with media queries so developers don't have to use the JavaScript API to show extra monetized content. 

I'd expect it to toggle in sync with the JavaScript API events.

```css
@media screen and (monetized: true) {
  .monetized-content {
    display: block;
  }
}
```

**Comment by mankins** [comment]
I like this idea on some levels, but wonder if `monetized` is more nuanced (monetized by ads, or a subscription or webmon...) maybe `webmon: true` narrows in on the monetization method better?

**Comment by marcoscaceres** [comment]
@mankins is right in that we should think about the use case first, but then we need to distill those down to “discrete” keywords.  

For context, in CSS land, "monetization" would a "media feature":
https://www.w3.org/TR/mediaqueries-5/#mq-features

A good example is "orientation", which takes either `"portrait | landscape"`

For us, it could be "none" and "active" or something. We will need to debate what these should be.

**Comment by AlexLakatos** [comment]
Looking at the spec, discrete values would make it easier to be used as a boolean as well. It would be more similar to "update" than "orientation" though. Maybe we can make the values related to the providers as well, even though there is only one provider for now.

```css
@media screen and (monetization) {
  .monetized-content {
    display: block;
  }
}

@media screen and not (monetization) {
  .monetized-content {
    display: block;
  }
}

@media screen and (monetization: provider) {
  .monetized-content {
    display: block;
  }
}

@media screen and (monetization: none) {
  .monetized-content {
    display: block;
  }
}
```
